### ISSUE TITLE
JSON::ParserError when watching key

### ISSUE THREAD

**Issue by Soulou** [ranjib/etcd-ruby#50]
Hello,

```
14:31:56 cache.1 | JSON::ParserError: A JSON text must at least contain two octets!
14:31:56 cache.1 | .../shared/bundle/ruby/2.1.0/gems/etcd-0.2.4/lib/etcd/response.rb:25:in `from_http_response'
14:31:56 cache.1 | .../shared/bundle/ruby/2.1.0/gems/etcd-0.2.4/lib/etcd/keys.rb:83:in `watch'
```

This error happen sometimes when using `event = client.watch key, recursive: true, timeout: 300`

I've the feeling it happens after the 300 seconds precisely, it may be interesting to catch the real error before parsing the body?

**Comment by ranjib** [comment]
closing due to inactivity, let me know if this issue persist.
